services:
  selenium-hub:
    image: selenium/hub:4.24.0-20240907
    networks:
      - selenium
  chrome:
    image: selenium/node-chrome:4.24.0-20240907
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=100
      - SE_NODE_SESSION_TIMEOUT=10800
    networks:
      - selenium
  firefox:
    image: selenium/node-firefox:4.24.0-20240907
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=100
      - SE_NODE_SESSION_TIMEOUT=10800
    networks:
      - selenium
networks:
  selenium: